#!/bin/sh
set -e
dbg='false'

usage() {
	cat<<EOF
   Sends a payload to Josuke server.
Usage:
 send-payload <JSON server conf> <hook name> <payload file> [options]
 send-payload <JSON server conf> -a url : prints the server base URL
 send-payload --help : prints this help.
Options:
 -a|--action: sets the action
   - send: sends a payload
   - url: prints the server base URL.
 --event <name>: sets the event in the HTTP request.
 --digest: sets the digest. Needs to exist in openssl: openssl dgst "-{digest}".
 --sign-prefix <true|false>: adds the digest in front of the signature, for instance: sha256=...
 --help: prints this help and exits.
 --test: prints only statements, does nothing.
 --debug: prints debug statements.
EOF
}
if test 0 = $# || test '--help' = "$1"; then usage; exit 0; fi

# Requires jq https://stedolan.github.io/jq/
jqExe='jq'
#jqExe='/p/dev/app/jq/jq-1.6-win32.exe'

action='send'
digest='sha256'
signPrefixEnabled='false'
eventHeaderValue=''


testMode='false'
optIndex=0
while test $# -gt 0; do
	case "$1" in
		-a|--action)   shift; action="$1";;
		--digest)      shift; digest="$1";;
		--event)       shift; eventHeaderValue="$1";;
		--sign-prefix) shift; if test 'true' = "$1"; then
			signPrefixEnabled='true'; else signPrefixEnabled='false'; fi;;
		--help)     usage; exit 0;;
		--test)     testMode='true';;
		--debug)    dbg='true';;
		-*) printf 'send-payload: unknown option: %s\n' "$1">&2; exit 1;;
		*) case "$optIndex" in
				0) serverConf="$1";;
				1) hookName="$1";;
				2) payloadFile="$1";;
				*) printf 'send-payload: unknown option: %s\n' "$1">&2; exit 1;;
			esac
			optIndex=$(( optIndex + 1 ));;
		esac
	shift
done

case "$action" in
	send|url) ;;
	*) printf 'send-payload: illegal action: %s\n' "$1">&2; exit 1;;
esac
# read values from the server configuration
getServerUrlFromConf() {
	port=$("$jqExe" -r 'if null == .port then empty else .port end' "$1")
	port="${port:-8082}"
	host=$("$jqExe" -r 'if null == .host then empty else .host end' "$1")
	host="${host:-127.0.0.1}"
	cert=$("$jqExe" -r 'if null == .cert then empty else .cert end' "$1")
	if test -z "$cert"; then
		protocol='http'
	else
		protocol='https'
	fi
	printf '%s' "$protocol://$host:$port"
}

if $signPrefixEnabled; then
	signPrefix="$digest="
else
	signPrefix=''
fi

if test -z "$serverConf"; then printf 'send-payload: missing configuration\n'>&2; exit 1; fi
if test 'url' = "$action"; then
	getServerUrlFromConf "$serverConf"
	exit 0
fi

if test -z "$hookName"; then printf 'send-payload: missing hook name\n'>&2; exit 1; fi
if test -z "$payloadFile"; then printf 'send-payload: missing payload\n'>&2; exit 1; fi

if test ! -f "$serverConf"; then
	printf 'send-payload: configuration not found: %s\n' "$serverConf">&2
	exit 1
fi
if test ! -f "$payloadFile"; then
	printf 'send-payload: payload not found: %s\n' "$payloadFile">&2
	exit 1
fi

# - JSON file
# - hook name
getHookTypeAndSecretFromConf() {
	#shellcheck disable=SC2016
	"$jqExe" -r --arg hookName "$2" '
	if null == .hook then
		error("Error: no hook defined\n")
	elif isempty(.hook[] | select(.name == $hookName)) then
		error("Error: no hook named \($hookName)\n")
	else
		.hook[] | select(.name == $hookName) | [ .type, .secret, .path ]
	end | @tsv' "$1"
}

serverUrl=$(getServerUrlFromConf "$serverConf")
record=$(getHookTypeAndSecretFromConf "$serverConf" "$hookName")
#if $dbg; then printf '#  record [%s]\n' "$record">&2; fi
hookType="${record%%	*}"
record="${record#*	}"
hookSecret="${record%%	*}"
record="${record#*	}"
hookPath="${record}"
unset record

if test -z "$hookType"; then
	printf 'send-payload: no hook type for hook name: %s\n' "$hookName">&2
	exit 1
fi

if $dbg; then {
	printf '#  url            %s\n' "${serverUrl}$hookPath"
	printf '#  hook type      %s\n' "$hookType"
	printf '#  hook name      %s\n' "$hookName"
	printf '#  hook secret    %s\n' "$hookSecret"
	if test -n "$signPrefix"; then
		printf '#  sign prefix    %s\n' "$signPrefix"
	fi
}>&2; fi
#exit 0

# - payload file
# - secret
signData() {
	openssl dgst "-$digest" -hmac "$2" "$1" | sed -E 's/^.[^=]+= (.+)$/\1/g'
}

payload="$(cat "$payloadFile")"


case "$hookType" in
	github)
		eventHeader='X-Github-Event'
		signHeader='X-Hub-Signature-256'
		signType='hmac256';;
	gogs)
		eventHeader='X-Gogs-Event'
		signHeader='X-Gogs-Signature'
		signType='hmac256';;
	bitbucket)
		eventHeader='X-Event-Key'
		test -z "$eventHeaderValue" && eventHeaderValue='repo:push'
		signHeader='X-Dummy-Signature'
		signType='';;
	webhook)
		eventHeader='X-Webhook-Event'
		signHeader='X-Webhook-Signature'
		signType='hmac256';;
	*) printf 'send-payload: unexpected hook type: %s\n' "$hookType">&2
	exit 1;;
esac

test -z "$eventHeaderValue" && eventHeaderValue='push'

if test -z "$signType"; then
	signature=''
elif test 'hmac256' = "$signType"; then
	signature=$(signData "$payloadFile" "$hookSecret")
else
	printf 'send-payload: unexpected sign type: %s\n' "$signType">&2
	exit 1
fi

if $dbg && test -n "$signature"; then {
	printf '#  signature      %s\n' "$signature"
}>&2; fi

if $testMode; then
	set -x
	: \
	curl "${serverUrl}$hookPath" \
	  -H 'Content-Type: application/json' \
	  -H "$eventHeader: $eventHeaderValue" \
	  -H "$signHeader: ${signPrefix}$signature" \
	  --data-raw "$payload"
else
	curl "${serverUrl}$hookPath" \
	  -H 'Content-Type: application/json' \
	  -H "$eventHeader: $eventHeaderValue" \
	  -H "$signHeader: ${signPrefix}$signature" \
	  --data-raw "$payload"
fi

